// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwimmingLesson.Data;

#nullable disable

namespace SwimmingLesson.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241214230822_MigrationName")]
    partial class MigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("swimmingLwssons.Entities.Course", b =>
                {
                    b.Property<int>("CodeCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeCourse"), 1L, 1);

                    b.Property<int>("CountLessons")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("CodeCourse");

                    b.ToTable("course");
                });

            modelBuilder.Entity("swimmingLwssons.Entities.Group", b =>
                {
                    b.Property<int>("CodeGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeGroup"), 1L, 1);

                    b.Property<int>("CodeCourse")
                        .HasColumnType("int");

                    b.Property<int>("CodeGuide")
                        .HasColumnType("int");

                    b.Property<int>("CountStudent")
                        .HasColumnType("int");

                    b.Property<int>("MaxStudent")
                        .HasColumnType("int");

                    b.HasKey("CodeGroup");

                    b.ToTable("group");
                });

            modelBuilder.Entity("swimmingLwssons.Entities.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<int>("Seniority")
                        .HasColumnType("int");

                    b.Property<string>("Tz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("swimmingLwssons.Entities.Lesson", b =>
                {
                    b.Property<int>("CodeLesson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeLesson"), 1L, 1);

                    b.Property<int>("CodeGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLesson")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FreeSwimming")
                        .HasColumnType("bit");

                    b.Property<string>("LearntInLesson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumLesson")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEndLesson")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStartLesson")
                        .HasColumnType("datetime2");

                    b.HasKey("CodeLesson");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("swimmingLwssons.Entities.Student", b =>
                {
                    b.Property<int>("CodeStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeStudent"), 1L, 1);

                    b.Property<int>("CodeCourse")
                        .HasColumnType("int");

                    b.Property<int>("CodeGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("HealthFund")
                        .HasColumnType("int");

                    b.Property<double>("Mark")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProofPayment")
                        .HasColumnType("int");

                    b.Property<string>("Tz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeStudent");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
